apiVersion: apps/v1
kind: StatefulSet 
metadata:
  name: mongo
  labels:
    app: mongo
spec:
  serviceName: "mongo"
  replicas: 1
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      labels:
        app: mongo
    spec:
      containers:
        - name: mongodb
          image: mongo:latest 
          ports:
            - containerPort: 27017
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: playlist-db-secret
                  key: MONGO_USER
            
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: playlist-db-secret 
                  key: MONGO_PASSWORD
                  
          volumeMounts:
            - name: mongo-storage
              mountPath: /data/db 
      
      volumes:
        - name: mongo-storage
          persistentVolumeClaim:
            claimName: mongo-data-pvc 